AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda functions for SFNX

Parameters: 
  Version: 
    Type: String
    Default: "v06"
  YahooAPIClientID: 
    Type: String
    Default: dj00aiZpPXh1Snk3OGlrRjRUciZzPWNvbnN1bWVyc2VjcmV0Jng9MWY-
  MainteinerEnailAddress: 
    Type: String
    Default: hiroki.y1124@gmail.com

Resources: 

  # ************************************************************
  # Lambda functions
  # ************************************************************

  FunctionGetCoordinates:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub sfnx-function_get-coordinates-${Version}
      CodeUri: ./services/get-coordinates/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 5
      MemorySize: 256
      Policies: 
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Environment:
        Variables:
          CLIENT_ID: !Ref YahooAPIClientID

  FunctionReverseAddress:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub sfnx-function_reverse-address-${Version}
      CodeUri: ./services/reverse-address/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 5
      MemorySize: 256
      Policies: 
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Environment:
        Variables:
          CLIENT_ID: !Ref YahooAPIClientID
    
  FunctionValidateQuery:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub sfnx-function_validate-query-${Version}
      CodeUri: ./services/validate-query/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 5
      MemorySize: 256
      Policies: 
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Environment:
        Variables:
          CLIENT_ID: !Ref YahooAPIClientID

  # ************************************************************
  # SNS Topics
  # ************************************************************

  TopicNotifyFail: 
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: "sfnx-topic-fail"
      DisplayName: "FAIL - GeoSearch"
      FifoTopic: False
      Subscription: 
        - Endpoint: !Ref MainteinerEnailAddress
          Protocol: email

  TopicNotifySuccess: 
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: "sfnx-topic-success"
      DisplayName: "SUCCESS - GeoSearch"
      FifoTopic: False
      Subscription: 
        - Endpoint: !Ref MainteinerEnailAddress
          Protocol: email