AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda functions for SFNX

Parameters: 
  Version: 
    Type: String
    Default: "v07"
  YahooAPIClientID: 
    Type: String
    Default: dj00aiZpPXh1Snk3OGlrRjRUciZzPWNvbnN1bWVyc2VjcmV0Jng9MWY-
  MainteinerEnailAddress: 
    Type: String
    Default: hiroki.y1124@gmail.com

Resources: 

  # ************************************************************
  # Lambda functions
  # ************************************************************

  FunctionGetCoordinates:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub sfnx-function_get-coordinates-${Version}
      CodeUri: ./services/get-coordinates/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 5
      MemorySize: 256
      Policies: 
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Environment:
        Variables:
          CLIENT_ID: !Ref YahooAPIClientID
      Timeout: 60
      Tracing: Active

  FunctionReverseAddress:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub sfnx-function_reverse-address-${Version}
      CodeUri: ./services/reverse-address/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 5
      MemorySize: 256
      Policies: 
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Environment:
        Variables:
          CLIENT_ID: !Ref YahooAPIClientID
      Timeout: 60
      Tracing: Active
    
  FunctionValidateQuery:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub sfnx-function_validate-query-${Version}
      CodeUri: ./services/validate-query/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 5
      MemorySize: 256
      Policies: 
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Environment:
        Variables:
          CLIENT_ID: !Ref YahooAPIClientID
      Timeout: 60
      Tracing: Active

  FunctionGetPlaceinfo:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub sfnx-function_get-placeinfo-${Version}
      CodeUri: ./services/get-placeinfo/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 5
      MemorySize: 256
      Policies: 
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Environment:
        Variables:
          CLIENT_ID: !Ref YahooAPIClientID
      Timeout: 60
      Tracing: Active

  FunctionGetWeather:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub sfnx-function_get-weather-${Version}
      CodeUri: ./services/get-weather/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 5
      MemorySize: 256
      Policies: 
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Environment:
        Variables:
          CLIENT_ID: !Ref YahooAPIClientID
      Timeout: 60
      Tracing: Active

  FunctionGetAltitude:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub sfnx-function_get-altitude-${Version}
      CodeUri: ./services/get-altitude/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 5
      MemorySize: 256
      Policies: 
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Environment:
        Variables:
          CLIENT_ID: !Ref YahooAPIClientID
      Timeout: 60
      Tracing: Active

  FunctionWriteDynamoDB:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub sfnx-function_write-dynamodb-${Version}
      CodeUri: ./services/write-dynamodb/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 5
      MemorySize: 256
      Policies: 
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Environment:
        Variables:
          CLIENT_ID: !Ref YahooAPIClientID
      Timeout: 60
      Tracing: Active

  # ************************************************************
  # SNS Topics
  # ************************************************************

  TopicNotifyFail: 
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: "sfnx-topic-fail"
      DisplayName: "FAIL - GeoSearch"
      FifoTopic: False
      Subscription: 
        - Endpoint: !Ref MainteinerEnailAddress
          Protocol: email

  TopicNotifySuccess: 
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: "sfnx-topic-success"
      DisplayName: "SUCCESS - GeoSearch"
      FifoTopic: False
      Subscription: 
        - Endpoint: !Ref MainteinerEnailAddress
          Protocol: email

  # ************************************************************
  # DynamoDB Table
  # ************************************************************

  DynamoDBTableAPIResults: 
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: "sfnx-DynamoDB-APIResultSets"
      AttributeDefinitions: 
        - AttributeName: "Coordinates"
          AttributeType: "S"
        - AttributeName: "CreatedTime"
          AttributeType: "S"
        - AttributeName: "AddressLv3"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "Coordinates"
          KeyType: "HASH"
        - AttributeName: "CreatedTime"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "GSI"
          KeySchema:
            - AttributeName: "AddressLv3"
              KeyType: "HASH"
          Projection:
            ProjectionType: "KEYS_ONLY"
          ProvisionedThroughput: 
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
